apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: dev.shared
  namespace: hierarchy # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/folder-ref: dev
spec:
  displayName: shared
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: prod.shared
  namespace: hierarchy # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/folder-ref: prod
spec:
  displayName: shared
