apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: bigip-instance
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: clf-bc-eap2 # kpt-set: ${project-id}
