apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  namespace: config-control
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: config-control
  project-id: clf-bc-eap2
